/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/llm/extract/item/values': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Extract Item Values
     * @description Extracts the properties with their corresponding values from the given item.
     */
    get: operations['extract_item_values_llm_extract_item_values_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/llm/synthesize/items/abstracts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Synthesize Abstracts For Question
     * @description Synthesizes a citable answer for a given research question from the abstracts of the given items.
     */
    get: operations['synthesize_abstracts_for_question_llm_synthesize_items_abstracts_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/llm/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Llm */
    post: operations['generate_llm_llm_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/llm/chat/completions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Completions Llm */
    post: operations['chat_completions_llm_llm_chat_completions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/add': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Index New Document
     * @description Index a new document in the vector database.
     */
    post: operations['index_new_document_index_add_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/add/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Index Documents
     * @description Index a list of documents in the vector database.
     */
    post: operations['bulk_index_documents_index_add_bulk_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Semantic Search
     * @description Searches for similar documents using ANN
     */
    get: operations['semantic_search_index_search_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/get/{document_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve Document
     * @description Get a single document from the vector store via its ID
     */
    get: operations['retrieve_document_index_get__document_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/explore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Explore Documents
     * @description Explore documents from the vector store using filters
     */
    get: operations['explore_documents_index_explore_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/recommend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Recommend Documents
     * @description Searches for similar documents using an ANN index
     */
    get: operations['recommend_documents_index_recommend_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Count Documents
     * @description Count documents from the vector store using regular filters
     */
    get: operations['count_documents_index_count_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/index/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Indices Info
     * @description Get information about the available indices.
     */
    get: operations['get_indices_info_index_info_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Data Stats
     * @description Get the statistics of the dataset.
     */
    get: operations['get_data_stats_backend_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/questions/recent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Recently Asked Questions
     * @description Get the recent questions.
     */
    get: operations['get_recently_asked_questions_backend_questions_recent_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/questions/popular': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Popular Asked Questions
     * @description Get the recent questions.
     */
    get: operations['get_popular_asked_questions_backend_questions_popular_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Backend Health
     * @description Get the health of the backend.
     */
    get: operations['get_backend_health_backend_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Backend Version
     * @description Get the backend version
     */
    get: operations['get_backend_version_backend_version_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BackendHealthResponse */
    BackendHealthResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__backend__BackendHealthResponse__Payload'];
    };
    /** BackendVersionResponse */
    BackendVersionResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__backend__BackendVersionResponse__Payload'];
    };
    /** BulkIndexRequest */
    BulkIndexRequest: {
      /**
       * Documents
       * @description The documents to be indexed
       */
      documents: components['schemas']['IndexRequest'][];
    };
    /** DBpediaEntity */
    DBpediaEntity: {
      /**
       * Uri
       * @description The URI of the DBpedia entity
       */
      uri: string;
      /**
       * Surface Form
       * @description The surface form of the DBpedia entity
       */
      surface_form: string;
    };
    /**
     * DatasetStats
     * @description The dataset statistics of the system.
     */
    DatasetStats: {
      /**
       * Num Items With Authors
       * @description The number of items with authors
       */
      num_items_with_authors?: number | null;
      /**
       * Num Items With Abstracts
       * @description The number of items with abstracts
       */
      num_items_with_abstracts?: number | null;
      /**
       * Num Items With Languages
       * @description The number of items with language tags
       */
      num_items_with_languages?: number | null;
      /**
       * Num Items With Topics
       * @description The number of items with topics
       */
      num_items_with_topics?: number | null;
      /**
       * Num Items With Subjects
       * @description The number of items with subjects
       */
      num_items_with_subjects?: number | null;
      /**
       * Num Items With Year
       * @description The number of items with year values
       */
      num_items_with_year?: number | null;
      /**
       * Num Items With Identifiers
       * @description The number of items with identifiers
       */
      num_items_with_identifiers?: number | null;
      /**
       * Num Items With Type
       * @description The number of items with a specific document type
       */
      num_items_with_type?: number | null;
      /**
       * Num Items With Issn
       * @description The number of items with an ISSN
       */
      num_items_with_issn?: number | null;
      /**
       * Num Items With Doi
       * @description The number of items with a DOI
       */
      num_items_with_doi?: number | null;
      /**
       * Num Items With Citations
       * @description The number of items with citation counts
       */
      num_items_with_citations?: number | null;
      /**
       * Num Items With Publication Date
       * @description The number of items with publication dates
       */
      num_items_with_publication_date?: number | null;
      /**
       * Num Items With Publisher
       * @description The number of items with publishers
       */
      num_items_with_publisher?: number | null;
      /**
       * Num Items With Journal
       * @description The number of items with journal names
       */
      num_items_with_journal?: number | null;
      /**
       * Num Items With Dbpedia Entities
       * @description The number of items with DBpedia entities
       */
      num_items_with_dbpedia_entities?: number | null;
    };
    /** EntityExtractions */
    EntityExtractions: {
      /**
       * Dbpedia
       * @description The DBpedia entities extracted from the item
       */
      dbpedia?: components['schemas']['DBpediaEntity'][] | null;
    };
    /** ExtractItemValuesFromPropertiesResponse */
    ExtractItemValuesFromPropertiesResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__llm__ExtractItemValuesFromPropertiesResponse__Payload'];
    };
    /** Extractions */
    'Extractions-Input': {
      /** @description The list of entities */
      entities: components['schemas']['EntityExtractions'];
    };
    /** Extractions */
    'Extractions-Output': {
      /** @description The list of entities */
      entities: components['schemas']['EntityExtractions'];
    };
    /** GenerationParameters */
    GenerationParameters: {
      /** Indexes */
      indexes: {
        [key: string]: number | undefined;
      };
      /** Collection */
      collection: Record<string, never>[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IndexRequest */
    IndexRequest: {
      /**
       * Id
       * @description The document ID, here is the coreID
       */
      id: string | number;
      /**
       * Doi
       * @description The DOI of the document
       */
      doi?: string | null;
      /**
       * Oai
       * @description The OAI of the document
       */
      oai?: string | null;
      /**
       * Title
       * @description The title of the document
       */
      title: string;
      /**
       * Date Published
       * @description The date published of the document
       */
      date_published?: string | null;
      /**
       * Abstract
       * @description The abstract of the document
       */
      abstract?: string | null;
      /**
       * Year
       * @description The year of the document
       */
      year?: number | string | null;
      /**
       * Issn
       * @description The ISSN of the document
       */
      issn?: string | null;
      /**
       * Full Text
       * @description The full text of the document
       */
      full_text?: string | null;
      /**
       * Subjects
       * @description A list of subjects of the document
       */
      subjects?: string[] | null;
      /**
       * Urls
       * @description A list of URLs of the document
       */
      urls?: string[] | null;
      /**
       * Identifiers
       * @description A list of identifiers of the document
       */
      identifiers?: string[] | null;
      /**
       * Topics
       * @description A list of topics of the document
       */
      topics?: string[] | null;
      /**
       * Download Url
       * @description The download URL of the document
       */
      download_url?: string | null;
      /**
       * Full Text Identifier
       * @description The full text identifier of the document
       */
      full_text_identifier?: string | null;
      /**
       * Pdf Hash Value
       * @description The PDF hash value of the document
       */
      pdf_hash_value?: string | null;
      /**
       * Raw Record Xml
       * @description The raw record XML of the document
       */
      raw_record_xml?: string | null;
      /**
       * Journals
       * @description A list of journals of the document
       */
      journals?: string[] | null;
      /**
       * Authors
       * @description A list of authors of the document
       */
      authors?: string[] | null;
      /**
       * Publisher
       * @description The publisher of the document
       */
      publisher?: string | null;
      /**
       * Relations
       * @description A list of relations of the document
       */
      relations?: string[] | null;
      /**
       * Contributors
       * @description A list of contributors of the document
       */
      contributors?: string[] | null;
      /**
       * Language
       * @description The language of the document
       */
      language?: string | null;
      /**
       * Citation Count
       * @description The citation count of the document
       */
      citation_count?: number | null;
      /**
       * Document Type
       * @description The inferred document type
       */
      document_type?: string | null;
      /** @description The automatic extractions from the item */
      extractions?: components['schemas']['Extractions-Input'] | null;
      /**
       * Source
       * @description The source of the document
       */
      source?: string | null;
    };
    /**
     * IndexingStats
     * @description The indexing statistics of the system.
     */
    IndexingStats: {
      /**
       * Num Indexed Vectors
       * @description The number of indexed vectors in the vector store
       */
      num_indexed_vectors: number;
      /** @description The configuration of the vectors in the vector store */
      vector_config: components['schemas']['VectorConfig'];
    };
    /** LLMChatMessage */
    LLMChatMessage: {
      /**
       * Role
       * @description The role of the message
       * @enum {string}
       */
      role: 'user' | 'assistant' | 'system';
      /**
       * Content
       * @description The content of the message
       */
      content: string;
    };
    /** LLMChatRequest */
    LLMChatRequest: {
      /**
       * Model
       * @description The model to use for generation. If not provided, the default model will be used
       */
      model?: string | null;
      /**
       * Stream
       * @description Whether to stream the output or not (default: True)
       * @default true
       */
      stream: boolean;
      /**
       * Messages
       * @description The messages to generate the response for
       */
      messages: components['schemas']['LLMChatMessage'][];
      /**
       * Temperature
       * @description The temperature to use for generation. Default is 0.5.
       * @default 0.5
       */
      temperature: number;
      /**
       * Top P
       * @description The nucleus sampling
       * @default 0.95
       */
      top_p: number;
      /**
       * Truncate
       * @description The maximum number of tokens to truncate
       * @default 150
       */
      truncate: number;
      /**
       * Stop
       * @description The stop token to use for generation
       */
      stop?: string | null;
      /**
       * Seed
       * @description The seed to use for generation
       */
      seed?: number | null;
      /**
       * Frequency Penalty
       * @description The frequency penalty
       * @default 1
       */
      frequency_penalty: number;
      /**
       * Presence Penalty
       * @description The presence penalty
       * @default 0.1
       */
      presence_penalty: number;
    };
    /** LLMGenerateRequest */
    LLMGenerateRequest: {
      /**
       * Prompt
       * @description The prompt to generate the response for
       */
      prompt: string;
      /**
       * System
       * @description The system to use for generation. None by default.
       */
      system?: string | null;
      /**
       * Model
       * @description The model to use for generation. If not provided, the default model will be used
       */
      model?: string | null;
      /**
       * Stream
       * @description Whether to stream the output or not (default: True)
       * @default true
       */
      stream: boolean;
      /**
       * Temperature
       * @description The temperature to use for generation. Default is 0.5.
       * @default 0.5
       */
      temperature: number;
      /**
       * Top K
       * @description The number of tokens to consider for the top-k sampling
       * @default 10
       */
      top_k: number;
      /**
       * Top N
       * @description The number of tokens to consider for the top-n sampling
       * @default 5
       */
      top_n: number;
      /**
       * Top P
       * @description The nucleus sampling
       * @default 0.95
       */
      top_p: number;
      /**
       * Truncate
       * @description The maximum number of tokens to truncate. Default is 150.
       * @default 150
       */
      truncate: number | null;
      /**
       * Context Size
       * @description The context size to use for generation
       */
      context_size?: number | null;
      /**
       * Context
       * @description The context for the short-term memory
       */
      context?: number[] | null;
      /**
       * Seed
       * @description The seed to use for generation
       */
      seed?: number | null;
    };
    /** LLMRawResponse */
    LLMRawResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Payload */
      payload: Record<string, never>;
    };
    /** PromptsUsed */
    PromptsUsed: {
      /** Indexes */
      indexes: {
        [key: string]: number | undefined;
      };
      /** Collection */
      collection: components['schemas']['ReproducibilityPrompt'][];
    };
    /** QdrantDictResponse */
    QdrantDictResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /**
       * Payload
       * @description The payload of the response
       */
      payload: Record<string, never>;
    };
    /** QdrantDocument */
    QdrantDocument: {
      /**
       * Id
       * @description The document ID, here is the coreID
       */
      id: string | number;
      /**
       * Doi
       * @description The DOI of the document
       */
      doi?: string | null;
      /**
       * Oai
       * @description The OAI of the document
       */
      oai?: string | null;
      /**
       * Title
       * @description The title of the document
       */
      title: string;
      /**
       * Date Published
       * @description The date published of the document
       */
      date_published?: string | null;
      /**
       * Abstract
       * @description The abstract of the document
       */
      abstract?: string | null;
      /**
       * Year
       * @description The year of the document
       */
      year?: number | string | null;
      /**
       * Issn
       * @description The ISSN of the document
       */
      issn?: string | null;
      /**
       * Full Text
       * @description The full text of the document
       */
      full_text?: string | null;
      /**
       * Subjects
       * @description A list of subjects of the document
       */
      subjects?: string[] | null;
      /**
       * Urls
       * @description A list of URLs of the document
       */
      urls?: string[] | null;
      /**
       * Identifiers
       * @description A list of identifiers of the document
       */
      identifiers?: string[] | null;
      /**
       * Topics
       * @description A list of topics of the document
       */
      topics?: string[] | null;
      /**
       * Download Url
       * @description The download URL of the document
       */
      download_url?: string | null;
      /**
       * Full Text Identifier
       * @description The full text identifier of the document
       */
      full_text_identifier?: string | null;
      /**
       * Pdf Hash Value
       * @description The PDF hash value of the document
       */
      pdf_hash_value?: string | null;
      /**
       * Raw Record Xml
       * @description The raw record XML of the document
       */
      raw_record_xml?: string | null;
      /**
       * Journals
       * @description A list of journals of the document
       */
      journals?: string[] | null;
      /**
       * Authors
       * @description A list of authors of the document
       */
      authors?: string[] | null;
      /**
       * Publisher
       * @description The publisher of the document
       */
      publisher?: string | null;
      /**
       * Relations
       * @description A list of relations of the document
       */
      relations?: string[] | null;
      /**
       * Contributors
       * @description A list of contributors of the document
       */
      contributors?: string[] | null;
      /**
       * Language
       * @description The language of the document
       */
      language?: string | null;
      /**
       * Citation Count
       * @description The citation count of the document
       */
      citation_count?: number | null;
      /**
       * Document Type
       * @description The inferred document type
       */
      document_type?: string | null;
      /** @description The automatic extractions from the item */
      extractions?: components['schemas']['Extractions-Output'] | null;
      /**
       * Source
       * @description The source of the document
       */
      source?: string | null;
    };
    /** QdrantListDocumentsResponse */
    QdrantListDocumentsResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /**
       * Payload
       * @description The list of documents that match the search
       */
      payload: components['schemas']['QdrantDocument'][];
    };
    /** QdrantPageResponse */
    QdrantPageResponse: {
      /**
       * Items
       * @description The list of items retrieved from Qdrant
       */
      items: components['schemas']['QdrantDocument'][];
      /**
       * Total Hits
       * @description The total number of documents that can be retrieved from Qdrant
       */
      total_hits: number;
      /**
       * Has More
       * @description Whether there are more documents to be retrieved from Qdrant
       */
      has_more: boolean;
      /**
       * Offset
       * @description The offset to start fetching documents from, could be int, str, or UUID
       */
      offset?: number | string | null;
    };
    /** QdrantPagedDocumentsResponse */
    QdrantPagedDocumentsResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** @description The page of documents that match the search */
      payload: components['schemas']['QdrantPageResponse'];
    };
    /** QdrantSingleDocumentResponse */
    QdrantSingleDocumentResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** @description The item that matches the selection criteria */
      payload: components['schemas']['QdrantDocument'];
    };
    /** QuestionRecord */
    QuestionRecord: {
      /**
       * Question
       * @description The question
       */
      question: string;
      /**
       * Frequency
       * @description The frequency of the question
       * @default 1
       */
      frequency: number;
      /**
       * Nsfw
       * @description Whether the question is NSFW
       * @default false
       */
      nsfw: boolean;
    };
    /** QuestionsResponse */
    QuestionsResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__backend__QuestionsResponse__Payload'];
    };
    /** ReproducibilityPrompt */
    ReproducibilityPrompt: {
      /**
       * System
       * @description The system that used the prompt
       */
      system: string;
      /**
       * User
       * @description The user that used the prompt
       */
      user: string;
      /**
       * Variables
       * @description The variables used with the prompt
       */
      variables: Record<string, never>;
    };
    /** StatisticsResponse */
    StatisticsResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__backend__StatisticsResponse__Payload'];
    };
    /** SynthesisAnswerOfQuestionFromAbstractsResponse */
    SynthesisAnswerOfQuestionFromAbstractsResponse: {
      /**
       * Uuid
       * Format: uuid
       */
      uuid: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      payload: components['schemas']['app__models__llm__SynthesisAnswerOfQuestionFromAbstractsResponse__Payload'];
    };
    /**
     * UsageStats
     * @description The usage statistics of the system.
     */
    UsageStats: {
      /**
       * Num Registered Users
       * @description The number of registered users in the system
       */
      num_registered_users: number;
      /**
       * Num Cache Hits
       * @description The number of cache hits in the system
       */
      num_cache_hits: number;
      /**
       * Num Collections
       * @description The number of user-created collections in the system
       */
      num_collections: number;
      /**
       * Num Collection Items
       * @description The number of items in bibtex imported items to the system
       */
      num_collection_items: number;
      /**
       * Num Saved Searches
       * @description The number of saved searches in the system
       */
      num_saved_searches: number;
      /**
       * Num Shared Links
       * @description The number of shared links in the system
       */
      num_shared_links: number;
      /**
       * Num Questions Asked
       * @description Approximate number of non-unique questions asked to the system
       */
      num_questions_asked: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VectorConfig
     * @description The configuration of the vectors in the vector store.
     */
    VectorConfig: {
      /**
       * Vector Size
       * @description The size of the vectors in the vector store
       */
      vector_size: number;
      /**
       * Distance Method
       * @description The method used to calculate the distance between vectors
       */
      distance_method: string;
    };
    /** Payload */
    app__models__backend__BackendHealthResponse__Payload: {
      /**
       * Message
       * @description The health status of the backend service
       */
      message: string;
      /**
       * Code
       * @description The status code of the health check
       */
      code: number;
    };
    /** Payload */
    app__models__backend__BackendVersionResponse__Payload: {
      /**
       * Version
       * @description The version of the backend service
       */
      version: string;
    };
    /** Payload */
    app__models__backend__QuestionsResponse__Payload: {
      /** Questions */
      questions: components['schemas']['QuestionRecord'][];
    };
    /** Payload */
    app__models__backend__StatisticsResponse__Payload: {
      indexing: components['schemas']['IndexingStats'];
      dataset: components['schemas']['DatasetStats'];
      usage: components['schemas']['UsageStats'];
    };
    /** Payload */
    app__models__llm__ExtractItemValuesFromPropertiesResponse__Payload: {
      /**
       * Item Id
       * @description The ID of the item to extract properties from
       */
      item_id: number | string;
      /**
       * Properties
       * @description The properties to extract from the item
       */
      properties: string[];
      /**
       * Values
       * @description The extracted values for the properties
       */
      values: {
        [key: string]: (string | (string | number)[] | number) | undefined;
      };
      /**
       * Extra
       * @description Extra values detected by the LLM
       */
      extra: {
        [key: string]: (string | (string | number)[] | number) | undefined;
      };
      /**
       * Seed
       * @description The seed used during extraction (if any)
       */
      seed?: number | null;
      /** @description The reproducibility parameters for the extraction */
      reproducibility?:
        | components['schemas']['app__models__llm__ExtractItemValuesFromPropertiesResponse__Reproducibility']
        | null;
    };
    /** Reproducibility */
    app__models__llm__ExtractItemValuesFromPropertiesResponse__Reproducibility: {
      /** @description The llm generation parameters */
      parameters: components['schemas']['GenerationParameters'];
      /** @description The prompt used for generation */
      prompts: components['schemas']['PromptsUsed'];
    };
    /** Payload */
    app__models__llm__SynthesisAnswerOfQuestionFromAbstractsResponse__Payload: {
      /**
       * Items Mapping
       * @description The item IDs mappings to the citations
       */
      items_mapping: {
        [key: string]: string | number;
      };
      /**
       * Collection Items Mapping
       * @description The collection item IDs mappings to the citations
       */
      collection_items_mapping: {
        [key: string]: string | number;
      };
      /**
       * Question
       * @description The question to synthesize the answer for
       */
      question: string;
      /**
       * Synthesis
       * @description The synthesized answer for the question
       */
      synthesis: string;
      /**
       * Seed
       * @description The seed used during synthesis (if any)
       */
      seed?: number | null;
      /** @description The reproducibility parameters for the synthesis */
      reproducibility?:
        | components['schemas']['app__models__llm__SynthesisAnswerOfQuestionFromAbstractsResponse__Reproducibility']
        | null;
    };
    /** Reproducibility */
    app__models__llm__SynthesisAnswerOfQuestionFromAbstractsResponse__Reproducibility: {
      /**
       * Parameters
       * @description The llm generation parameters
       */
      parameters: Record<string, never>;
      /** @description The prompt used for generation */
      prompt: components['schemas']['ReproducibilityPrompt'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  extract_item_values_llm_extract_item_values_get: {
    parameters: {
      query: {
        /** @description The properties to extract from the item */
        properties: string[];
        /** @description The item ID to extract the values from */
        item_id?: number | string | null;
        /** @description The custom collection item ID to extract the values from */
        collection_item_id?: string | null;
        /** @description Whether to invalidate the cache for the item */
        invalidate_cache?: boolean;
        /** @description The language of the response. Should be one of the following: en, de, es, fr, it, pt, nl, ru, ja, ar, fa, tr, ko, zh, hi, vi, id */
        response_language?: string | null;
        /** @description The seed to use during extraction */
        seed?: number | null;
        /** @description Whether to include the generation parameters and prompts for the response */
        reproducibility?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtractItemValuesFromPropertiesResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  synthesize_abstracts_for_question_llm_synthesize_items_abstracts_get: {
    parameters: {
      query: {
        /** @description The question to synthesize the abstracts for */
        question: string;
        /** @description The item ID to use during synthesis */
        item_ids?: (number | string)[];
        /** @description The custom collection item IDs to use during synthesis */
        collection_item_ids?: (number | string)[];
        /** @description Whether to invalidate the cache for the item */
        invalidate_cache?: boolean;
        /** @description The language of the response. Should be one of the following: en, de, es, fr, it, pt, nl, ru, ja, ar, fa, tr, ko, zh, hi, vi, id */
        response_language?: string | null;
        /** @description The seed to use during extraction */
        seed?: number | null;
        /** @description Whether to include the generation parameters and prompts for the response */
        reproducibility?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SynthesisAnswerOfQuestionFromAbstractsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_llm_llm_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LLMGenerateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LLMRawResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  chat_completions_llm_llm_chat_completions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LLMChatRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LLMRawResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  index_new_document_index_add_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IndexRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantDictResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bulk_index_documents_index_add_bulk_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkIndexRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  semantic_search_index_search_get: {
    parameters: {
      query: {
        /** @description The text to search for */
        query: string;
        /** @description The maximum number of documents to return */
        limit?: number;
        /** @description The offset to start fetching documents from */
        offset?: number | null;
        /** @description The criteria to filter the search results */
        filter?: string | null;
        /** @description The sources to search from */
        focus?: string[] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantPagedDocumentsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  retrieve_document_index_get__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantSingleDocumentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  explore_documents_index_explore_get: {
    parameters: {
      query: {
        /** @description The criteria to filter the search results */
        filter: string;
        /** @description The maximum number of documents to return */
        limit?: number;
        /** @description The offset to start fetching documents from */
        offset?: string | null;
        /** @description The payload field to order by */
        order_by?: string | null;
        /** @description The sources to explore documents from */
        focus?: string[] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantPagedDocumentsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  recommend_documents_index_recommend_get: {
    parameters: {
      query: {
        /** @description The document IDs to be used for recommendations */
        document_ids: string[];
        /** @description The document IDs to be avoided for recommendations */
        avoid_ids?: string[] | null;
        /** @description The maximum number of documents to return */
        limit?: number;
        /** @description The offset to start fetching documents from */
        offset?: number | null;
        /** @description The criteria to filter the search results */
        filter?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantListDocumentsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  count_documents_index_count_get: {
    parameters: {
      query?: {
        /** @description The criteria to filter the search results */
        filter?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantDictResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_indices_info_index_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QdrantDictResponse'];
        };
      };
    };
  };
  get_data_stats_backend_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatisticsResponse'];
        };
      };
    };
  };
  get_recently_asked_questions_backend_questions_recent_get: {
    parameters: {
      query?: {
        /** @description the number of recent questions to return */
        count?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_popular_asked_questions_backend_questions_popular_get: {
    parameters: {
      query?: {
        /** @description the number of popular questions to return */
        count?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_backend_health_backend_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BackendHealthResponse'];
        };
      };
    };
  };
  get_backend_version_backend_version_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BackendVersionResponse'];
        };
      };
    };
  };
}
